### ISSUE TITLE
phabricator.local service build error and start error

### ISSUE THREAD

**Issue by fouvy** [altendky/docker-compose-phabricator-jenkins#1]
comment this line in phabricator/Dockfile, it seems unused. then build docker will pass, 

`COPY packages/phabricatormod /tmp/bitnami/pkg/cache/phabricatormod-linux-x64-debian-8`

Error executing 'postInstallation': The admin password configured is one of the most common passwords in use. Choose a stronger password.
change this line in phabricator/Dockfile

    PHABRICATOR_PASSWORD="password"

to this:

    PHABRICATOR_PASSWORD="bitnami1"

**Comment by altendky** [comment]
@fouvy, thanks for catching this.  Should be fixed by cc0cd037736f9351b7b17dc308ac630e2e21e8dc.

**Comment by fouvy** [comment]
@altendky greate job!

**Comment by amosbird** [comment]
btw, specifying a new user PHABRICATOR_USER doesn't make it admin

**Comment by altendky** [comment]
That would only be relevant for the initial startup. After that you manage users within Phabricator.

**Comment by altendky** [comment]
@fouvy, should this issue be closed?

**Comment by fouvy** [comment]
@altendky sure.
